{{ if .Values.configMap }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
{{ toYaml .Values.configMap | indent 2 }}

{{end}}
