apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.serviceName }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
